# 2.2 数据操作

In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[7.1118e-04, 1.7444e+28, 7.3909e+22],
        [1.8727e+31, 1.4182e-19, 4.6168e+24],
        [4.2964e+24, 1.2514e-14, 8.9634e-33],
        [7.1345e+31, 7.1118e-04, 1.7444e+28],
        [7.3909e+22, 1.8727e+31, 1.3179e+25]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0540, 0.2484, 0.2738],
        [0.3477, 0.5699, 0.6856],
        [0.0873, 0.6959, 0.9278],
        [0.7046, 0.6140, 0.4660],
        [0.4286, 0.1635, 0.9315]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0471, 0.8849, 0.0319],
        [0.8052, 0.1555, 0.3111],
        [0.9911, 0.7185, 0.5312],
        [0.4111, 0.8994, 0.4216],
        [0.4958, 0.8640, 0.6938]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.6956, 1.6051, 0.0622],
        [0.9020, 0.5308, 1.0569],
        [1.9150, 0.8847, 1.0863],
        [0.7778, 0.9729, 0.4255],
        [1.1466, 1.7687, 1.1816]])


In [9]:
print(torch.add(x, y))

tensor([[0.6956, 1.6051, 0.0622],
        [0.9020, 0.5308, 1.0569],
        [1.9150, 0.8847, 1.0863],
        [0.7778, 0.9729, 0.4255],
        [1.1466, 1.7687, 1.1816]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6956, 1.6051, 0.0622],
        [0.9020, 0.5308, 1.0569],
        [1.9150, 0.8847, 1.0863],
        [0.7778, 0.9729, 0.4255],
        [1.1466, 1.7687, 1.1816]])


In [11]:
# adds x to y(inplace)
y.add_(x)
print(y)

tensor([[0.6956, 1.6051, 0.0622],
        [0.9020, 0.5308, 1.0569],
        [1.9150, 0.8847, 1.0863],
        [0.7778, 0.9729, 0.4255],
        [1.1466, 1.7687, 1.1816]])


In [12]:
y = x[0,:]
y += 1
print(y)
print(x[0,:])

tensor([1.0471, 1.8849, 1.0319])
tensor([1.0471, 1.8849, 1.0319])


In [13]:
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [14]:
x += 1
print(x)
print(y)

tensor([[2.0471, 2.8849, 2.0319],
        [1.8052, 1.1555, 1.3111],
        [1.9911, 1.7185, 1.5312],
        [1.4111, 1.8994, 1.4216],
        [1.4958, 1.8640, 1.6938]])
tensor([2.0471, 2.8849, 2.0319, 1.8052, 1.1555, 1.3111, 1.9911, 1.7185, 1.5312,
        1.4111, 1.8994, 1.4216, 1.4958, 1.8640, 1.6938])


In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[1.0471, 1.8849, 1.0319],
        [0.8052, 0.1555, 0.3111],
        [0.9911, 0.7185, 0.5312],
        [0.4111, 0.8994, 0.4216],
        [0.4958, 0.8640, 0.6938]])
tensor([2.0471, 2.8849, 2.0319, 1.8052, 1.1555, 1.3111, 1.9911, 1.7185, 1.5312,
        1.4111, 1.8994, 1.4216, 1.4958, 1.8640, 1.6938])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3451])
-0.34512054920196533


In [17]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before)

True


In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [23]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# 2.3 自动求梯度

In [24]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [25]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [26]:
print(x.is_leaf, y.is_leaf)

True False


In [27]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [28]:
a = torch.randn(2, 2) # 默认 require_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [29]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [30]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [31]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [32]:
out2 = x.sum()
print(out2)
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor(4., grad_fn=<SumBackward0>)
tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [34]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)


In [36]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [37]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x **3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [38]:
y3.backward()
print(x.grad)

tensor(2.)


In [39]:
y2.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [41]:
x = torch.ones(1, requires_grad=True)
print(x.data)
print(x.data.requires_grad)

y = 2 * x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
