In [2]:
import torch

In [3]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y, x-y, x*y, x/y, x**y

(tensor([5.]), tensor([1.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [6]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [7]:
len(x)

4

In [8]:
x.shape

torch.Size([4])

In [10]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [13]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [14]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [18]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [19]:
A+B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [22]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a+X, (a*X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]), tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [23]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [25]:
A = torch.arange(20*2).reshape(2,5,4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [27]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]), torch.Size([5, 4]))

In [29]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]), torch.Size([2, 4]))

In [30]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [35]:
A.sum(axis=[0,1]).shape

torch.Size([4])

In [33]:
A.sum()/A.numel()

tensor(19.5000)

In [37]:
# sum_A = A.sum(axis=1, keepdima=True)
# A / sum_A

In [38]:
A.cumsum(axis=0)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]])

In [40]:
y = torch.ones(4, dtype=torch.float32)
x, y
# torch.dot(x, y)

(tensor([0, 1, 2, 3]), tensor([1., 1., 1., 1.]))

In [41]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [42]:
torch.abs(u).sum()

tensor(7.)

In [43]:
torch.norm(torch.ones((4, 9)))

tensor(6.)